.PHONY: clean all
all:
	@echo "# Use the script 'compile.sh' to compile an example."
	@echo "# For example:"
	@echo "#   sh compile.sh ex_circle.ml"

clean:
	$(RM) *.[oa] *.cm[ixoa] *.cmx[as] *.so *.bin *.exe *.opt *.byte
